/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package latianFx;

/**
 *
 * @author WINDOWS 10
 */
public class FrameIdealTubuh extends javax.swing.JFrame {

    /**
     * Creates new form FrameIdealTubuh
     */
    public FrameIdealTubuh() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel8 = new javax.swing.JLabel();
        JenisKelamin = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        idberat = new javax.swing.JTextField();
        idnama = new javax.swing.JTextField();
        idtinggi = new javax.swing.JTextField();
        rdblakilaki = new javax.swing.JRadioButton();
        rdbperempuan = new javax.swing.JRadioButton();
        buttonhitung = new javax.swing.JButton();
        buttoncobaulang = new javax.swing.JButton();
        buttonkeluar = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        idideal = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        idhasil = new javax.swing.JTextField();
        idsaran = new javax.swing.JTextField();

        jLabel8.setText("jLabel8");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(102, 255, 255));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        jLabel1.setText("Aplikasi Cek Ideal");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(130, 10, 150, 21);

        jLabel2.setFont(new java.awt.Font("Tw Cen MT", 0, 12)); // NOI18N
        jLabel2.setText("Tinggi");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(20, 70, 28, 14);

        jLabel3.setFont(new java.awt.Font("Tw Cen MT", 0, 12)); // NOI18N
        jLabel3.setText("Jenis Kelamin");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(20, 130, 80, 14);

        jLabel4.setFont(new java.awt.Font("Tw Cen MT", 0, 12)); // NOI18N
        jLabel4.setText("Nama");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(20, 40, 28, 14);

        jLabel5.setFont(new java.awt.Font("Tw Cen MT", 0, 12)); // NOI18N
        jLabel5.setText("Berat");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(20, 100, 25, 14);

        idberat.setFont(new java.awt.Font("Tw Cen MT", 0, 12)); // NOI18N
        jPanel1.add(idberat);
        idberat.setBounds(90, 100, 50, 20);

        idnama.setFont(new java.awt.Font("Tw Cen MT", 0, 12)); // NOI18N
        jPanel1.add(idnama);
        idnama.setBounds(90, 40, 90, 20);

        idtinggi.setFont(new java.awt.Font("Tw Cen MT", 0, 12)); // NOI18N
        jPanel1.add(idtinggi);
        idtinggi.setBounds(90, 70, 50, 20);

        JenisKelamin.add(rdblakilaki);
        rdblakilaki.setFont(new java.awt.Font("Tw Cen MT", 0, 12)); // NOI18N
        rdblakilaki.setText("Laki-laki");
        jPanel1.add(rdblakilaki);
        rdblakilaki.setBounds(140, 130, 65, 23);

        JenisKelamin.add(rdbperempuan);
        rdbperempuan.setFont(new java.awt.Font("Tw Cen MT", 0, 12)); // NOI18N
        rdbperempuan.setText("Perempuan");
        jPanel1.add(rdbperempuan);
        rdbperempuan.setBounds(250, 130, 79, 23);

        buttonhitung.setFont(new java.awt.Font("Tw Cen MT", 0, 12)); // NOI18N
        buttonhitung.setText("Hitung");
        buttonhitung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonhitungActionPerformed(evt);
            }
        });
        jPanel1.add(buttonhitung);
        buttonhitung.setBounds(40, 170, 61, 23);

        buttoncobaulang.setFont(new java.awt.Font("Tw Cen MT", 0, 12)); // NOI18N
        buttoncobaulang.setText("Coba ulang");
        buttoncobaulang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttoncobaulangActionPerformed(evt);
            }
        });
        jPanel1.add(buttoncobaulang);
        buttoncobaulang.setBounds(150, 170, 90, 23);

        buttonkeluar.setFont(new java.awt.Font("Tw Cen MT", 0, 12)); // NOI18N
        buttonkeluar.setText("Keluar");
        buttonkeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonkeluarActionPerformed(evt);
            }
        });
        jPanel1.add(buttonkeluar);
        buttonkeluar.setBounds(280, 170, 63, 23);

        jLabel6.setFont(new java.awt.Font("Tw Cen MT", 0, 12)); // NOI18N
        jLabel6.setText("Ideal");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(20, 200, 25, 14);

        idideal.setFont(new java.awt.Font("Tw Cen MT", 0, 12)); // NOI18N
        jPanel1.add(idideal);
        idideal.setBounds(90, 200, 50, 20);

        jLabel7.setFont(new java.awt.Font("Tw Cen MT", 0, 12)); // NOI18N
        jLabel7.setText("kg");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(150, 200, 11, 14);

        jLabel9.setFont(new java.awt.Font("Tw Cen MT", 0, 12)); // NOI18N
        jLabel9.setText("cm");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(150, 70, 20, 20);

        jLabel10.setFont(new java.awt.Font("Tw Cen MT", 0, 12)); // NOI18N
        jLabel10.setText("kg");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(150, 100, 11, 14);

        jLabel11.setFont(new java.awt.Font("Tw Cen MT", 0, 12)); // NOI18N
        jLabel11.setText("Saran");
        jPanel1.add(jLabel11);
        jLabel11.setBounds(20, 230, 27, 14);

        idhasil.setFont(new java.awt.Font("Tw Cen MT", 0, 12)); // NOI18N
        jPanel1.add(idhasil);
        idhasil.setBounds(20, 250, 230, 30);

        idsaran.setFont(new java.awt.Font("Tw Cen MT", 0, 12)); // NOI18N
        jPanel1.add(idsaran);
        idsaran.setBounds(20, 290, 230, 30);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 321, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonkeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonkeluarActionPerformed
        // TODO add your handling code here:
        dispose();
        System.exit(0);
    }//GEN-LAST:event_buttonkeluarActionPerformed

    private void buttoncobaulangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttoncobaulangActionPerformed
        // TODO add your handling code here:
        idnama.setText("");
        idberat.setText("");
        idtinggi.setText("");
        idideal.setText("");
        idhasil.setText("");
        idsaran.setText("");
        JenisKelamin.clearSelection();
    }//GEN-LAST:event_buttoncobaulangActionPerformed

    private void buttonhitungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonhitungActionPerformed
        // TODO add your handling code here:
        double t = Double.valueOf(idtinggi.getText());
        double b = Double.valueOf(idberat.getText());
        double h = 0;
        String nama = idnama.getText();
        
        if(rdblakilaki.isSelected())
        {
            h = (t - 100);
        }
        else if(rdbperempuan.isSelected())
        {
            h = (t - 104);
        }
        String temp = Double.toString(h);
        
        if(h<b)
        {
            idideal.setText(temp);
            idhasil.setText("Maaf "+nama+" Sepertinya Anda Overweight");
            idsaran.setText("Perbanyak olahraga ya^^");
        }
        
        else if(h>b)
        {
            idideal.setText(temp);
            idhasil.setText("Maaf "+nama+" Sepertinya Anda Underweight");
            idsaran.setText("Perbanyak asupan gizi dan nutrisi Anda ya^^");
        }
        else
        {
            idideal.setText(temp);
            idhasil.setText("Tubuh Anda Ideal");
            idsaran.setText("Pertahankan ya^^");
        }
    }//GEN-LAST:event_buttonhitungActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrameIdealTubuh.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrameIdealTubuh.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrameIdealTubuh.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrameIdealTubuh.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrameIdealTubuh().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup JenisKelamin;
    private javax.swing.JButton buttoncobaulang;
    private javax.swing.JButton buttonhitung;
    private javax.swing.JButton buttonkeluar;
    private javax.swing.JTextField idberat;
    private javax.swing.JTextField idhasil;
    private javax.swing.JTextField idideal;
    private javax.swing.JTextField idnama;
    private javax.swing.JTextField idsaran;
    private javax.swing.JTextField idtinggi;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton rdblakilaki;
    private javax.swing.JRadioButton rdbperempuan;
    // End of variables declaration//GEN-END:variables
}
